import { forwardRef } from "react";
import styles from "./ReportStepper.module.css";
import { type FullReport } from "./schemas/fullReport";

interface MedicalReportProps {
  data: Partial<FullReport>;
}

const MedicalReport = forwardRef<HTMLDivElement, MedicalReportProps>(({ data }, ref) => {
  return (
    <div className={styles.reportWrapper} ref={ref}>
      <div className={styles.header}>
        <h1>MontuCore Medical Report</h1>
      </div>

      <section className={styles.section}>
        <h2>Patient Information</h2>
       <div className={styles.row}><span>Pain Level:</span> <span>{data.painLevel || "-"}</span></div>
      </section>

      <section className={styles.section}>
        <h2>Symptoms</h2>
        {data.symptoms?.length ? (
          data.symptoms.map((s: string, i: number) => <div key={i} className={styles.row}><span>Symptom {i + 1}:</span> <span>{s}</span></div>)
        ) : (
          <div className={styles.row}>No symptoms reported</div>
        )}
      </section>

      <section className={styles.section}>
        <h2>Assessment</h2>
        <div className={styles.row}><span>Diagnosis:</span> <span>{data.diagnosis || "-"}</span></div>
        <div className={styles.row}><span>Injury Type:</span> <span>{data.injuryType || "-"}</span></div>
        <div className={styles.row}><span>Severity:</span> <span>{data.severity || "-"}</span></div>
        <div className={styles.row}><span>Recommended Imaging:</span> <span>{data.recommendedImaging?.join(", ") || "-"}</span></div>
      </section>

      <section className={styles.section}>
        <h2>Treatment Plan</h2>
        <div className={styles.row}><span>Immediate Actions:</span> <span>{data.immediateActions || "-"}</span></div>
        <div className={styles.row}><span>Medication:</span> <span>{data.medication || "-"}</span></div>
        <div className={styles.row}><span>Rehabilitation Plan:</span> <span>{data.rehabPlan || "-"}</span></div>
        <div className={styles.row}><span>Follow-up Date:</span> <span>{data.followUpDate || "-"}</span></div>
      </section>

      <footer className={styles.footer}>
        This report is generated by MontuCore Medical System
      </footer>
    </div>
  );
});

export default MedicalReport;
