import { forwardRef } from "react";
import styles from "./ReportStepper.module.css";
import { type FullReport } from "./schemas/fullReport";
import type { TreatmentData } from "../../level-2/DetailsOverlay/TreatmentOverlay";

interface MedicalReportProps {
  data: Partial<FullReport>;
}

const MedicalReport = forwardRef<HTMLDivElement, MedicalReportProps>(({ data }, ref) => {
  const treatments: TreatmentData[] = (data.treatment || []).map((t: any) => ({
    id: t.id,
    type: t.type || "-",
    description: t.description || "-",
    providerName: t.providerName || "-",
    date: t.date || "-",
    cost: t.cost ?? 0,
  }));

  return (
    <div className={styles.reportWrapper} ref={ref}>
      <div className={styles.header}>
        <h1>MontuCore Medical Report</h1>
      </div>

      <section className={styles.section}>
        <h2>Case Information</h2>
        <div className={styles.row}><span>Status:</span> <span>{data.caseStatus || "-"}</span></div>
        <div className={styles.row}><span>Pain Level:</span> <span>{data.painLevel ?? "-"}</span></div>
      </section>

      <section className={styles.section}>
        <h2>Symptoms & Notes</h2>
        {data.symptoms?.length ? (
          data.symptoms.map((s: string, i: number) => (
            <div key={i} className={styles.row}>
              <span>Symptom {i + 1}:</span> <span>{s}</span>
            </div>
          ))
        ) : (
          <div className={styles.row}>No symptoms reported</div>
        )}
        <div className={styles.row}><span>Additional Notes:</span> <span>{data.Notes || "-"}</span></div>
      </section>

      <section className={styles.section}>
        <h2>Assessment</h2>
        <div className={styles.row}><span>Diagnosis:</span> <span>{data.diagnosis || "-"}</span></div>
        <div className={styles.row}><span>Injury Type:</span> <span>{data.injuryType || "-"}</span></div>
        <div className={styles.row}>
          <span>Severity:</span> 
          <span>
            {data.severity ? data.severity.charAt(0) + data.severity.slice(1).toLowerCase() : "-"}
          </span>
        </div>
      </section>

      <section className={styles.section}>
        <h2>Imaging Exam</h2>
        {Array.isArray(data.exam) && data.exam.length > 0 ? (
          data.exam.map((e, i) => (
            <div key={i} className={styles.row} style={{ flexDirection: "column", marginBottom: "0.5rem" }}>
              <div><span>Modality:</span> <span>{e.modality?.join(", ") || "-"}</span></div>
              <div><span>Body Part:</span> <span>{e.bodyPart || "-"}</span></div>
            </div>
          ))
        ) : (
          <div className={styles.row}>No imaging exams reported</div>
        )}
      </section>

      <section className={styles.section}>
        <h2>Treatments</h2>
        {treatments.length > 0 ? (
          treatments.map((t, i) => (
            <div key={i} className={styles.row} style={{ flexDirection: "column", borderBottom: "1px solid #eee", paddingBottom: "0.5rem", marginBottom: "0.5rem" }}>
              <div><span>Type:</span> <span>{t.type}</span></div>
              <div><span>Description:</span> <span>{t.description}</span></div>
              <div><span>Provider:</span> <span>{t.providerName}</span></div>
              <div><span>Date:</span> <span>{t.date}</span></div>
              <div>
                <span>Cost:</span> 
                <span style={{ fontWeight: "bold" }}>
                   {t.cost !== undefined ? `$${t.cost.toLocaleString()}` : "-"}
                </span>
              </div>
            </div>
          ))
        ) : (
          <div className={styles.row}>No treatments reported</div>
        )}
      </section>

      <footer className={styles.footer}>
        This report is generated by MontuCore HIS system
      </footer>
    </div>
  );
});

export default MedicalReport;